{
 "title": "New OpenEBS Dashboard 3",
 "description": "This dashboard gives overview of OpenEBS installation in cluster.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } },
   { "name": "duration", "query": "10m,20m,30m,1h,2h,5h,1d" },
   { "name": "namespace", "query": "openebs,default,test-dashboard" }
  ]
 },
 "panels": [
  {
   "title": "Pool Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "openebs_pool_status{namespace=\"$namespace\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "pod count by nodes of $namespace in $cluster cluster",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (node)(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage by Pods in $namespace  in $cluster cluster",
   "type": "timeseries",
   "description": "This panel shows mem usage of  pods across $namespace in $cluster cluster.\n\nMemory utilization is easily tracked with container_memory_usage_bytes, however, this metric also includes cached (think filesystem cache) items that can be evicted under memory pressure. That's why we are using a  better metric: container_memory_working_set_bytes as this is what the OOM killer is watching for.\n",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": " (sum(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\", namespace=\"$namespace\"}))",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU usage by Pods in $namespace  in $cluster cluster",
   "type": "timeseries",
   "description": "This panel shows mem usage of  pods across $namespace in $cluster cluster.\n\nMemory utilization is easily tracked with container_memory_usage_bytes, however, this metric also includes cached (think filesystem cache) items that can be evicted under memory pressure. That's why we are using a  better metric: container_memory_working_set_bytes as this is what the OOM killer is watching for.\n",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory details in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " (sum(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\", namespace=\"$namespace\"}))",
     "legendFormat": "Memory used"
    },
    {
     "expr": " (sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}))",
     "legendFormat": "Memory requests"
    },
    {
     "expr": " (sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}))",
     "legendFormat": "Memory limits"
    }
   ]
  },
  {
   "title": "Memory usage by pods in namespace $namespace and cluster $cluster",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": " kube_pod_container_status_ready{namespace=\"$namespace\"} == 1"
    },
    {
     "expr": "sum\n  by(pod) (container_memory_usage_bytes{container!=\"POD\",namespace=\"$namespace\"})"
    },
    {
     "expr": "kube_pod_info{namespace=\"$namespace\"}"
    },
    {
     "expr": "time() - kube_pod_start_time{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU details in namespace $namespace",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) * 100 ",
     "legendFormat": "CPU used"
    },
    {
     "expr": "sum(rate(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}[1m])) * 100 ",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "sum(rate(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}[1m])) * 100 ",
     "legendFormat": "CPU limits"
    }
   ]
  },
  {
   "title": "persistentvolumeclaim ",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kube_persistentvolume_status_phase{cluster=\"$cluster\"}",
     "legendFormat": "{{persistentvolumeclaim}}:{{phase}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OpenEBS data plane availability over [$duration]",
   "type": "singlestat",
   "description": "OpenEBS SLO is based on no. of running data plane OpenEBS pods over a period of time. Below pods have been taken into consideration which impacts data availability hosted on OpenEBS:\n\n1. cstor pods\n2. jiva ctrl and replica pods\n3. nfs provisioner\n",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 29 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "displayType": "Regular",
     "expr": "avg(avg_over_time((sum without ()(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"pvc.*.ctrl.*|pvc.*.rep.*|pvc.*.target.*\"}) / count without ()(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"pvc.*.ctrl.*|pvc.*.rep.*|pvc.*.target.*\"}))[$duration:5m]))",
     "valueHandler": "Number Threshold"
    },
    {}
   ]
  },
  {
   "title": "Memory  details in namespace $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": " (sum(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU  details in namespace $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod container restarts in OpenEBS in $duration",
   "type": "timeseries",
   "description": "This panel shows container restarts in $cluster cluster per namespace during $duration.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=\"$namespace\"}[2m]) ",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}